name: flutter_scrcpy_gui
description: A GUI tool for scrcpy with device-specific configurations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^13.0.0
  flutter_animate: ^4.3.0
  device_info_plus: ^9.1.1
  process_run: ^1.2.4
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  win32: ^5.13.0
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
