name: flutter_scrcpy_gui
description: A GUI tool for scrcpy with device-specific configurations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  go_router: ^15.2.0
  flutter_animate: ^4.5.2
  device_info_plus: ^11.4.0
  process_run: ^1.2.4
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  win32: ^5.14.0
  window_manager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
