import 'package:freezed_annotation/freezed_annotation.dart';

part 'device_config.freezed.dart';
part 'device_config.g.dart';

@freezed
class DeviceConfig with _$DeviceConfig {
  const factory DeviceConfig({
    required String deviceId,
    String? adbPath,
    String? scrcpyPath,
    @Default(1920) int maxSize,
    @Default(0) int bitRate,
    @Default(false) bool stayAwake,
    @Default(false) bool turnScreenOff,
    @Default(false) bool showTouches,
    @Default(false) bool fullscreen,
    @Default(false) bool alwaysOnTop,
    @Default(false) bool disableScreensaver,
    @Default(false) bool noAudio,
    @Default(false) bool noVideo,
    @Default(false) bool noControl,
    @Default(false) bool noDisplay,
    String? encoder,
    String? crop,
    int? lockVideoOrientation,
    int? maxFps,
    String? renderDriver,
    String? windowTitle,
    int? windowX,
    int? windowY,
    int? windowWidth,
    int? windowHeight,
    int? keyRepeat,
    int? keyRepeatDelay,
    String? shortcutMod,
    String? record,
    String? recordFormat,
    @Default(false) bool noPowerOn,
    @Default(false) bool noPowerOff,
    @Default(false) bool noPowerOffOnClose,
    @Default(false) bool noPowerOffOnDisconnect,
    @Default(false) bool noPowerOffOnError,
    @Default(false) bool noPowerOffOnExit,
    @Default(false) bool noPowerOffOnStop,
    @Default(false) bool noPowerOffOnSuspend,
    @Default(false) bool noPowerOffOnResume,
    @Default(false) bool noPowerOffOnLock,
    @Default(false) bool noPowerOffOnUnlock,
    @Default(false) bool noPowerOffOnScreenOff,
    @Default(false) bool noPowerOffOnScreenOn,
    @Default(false) bool noPowerOffOnBatteryLow,
    @Default(false) bool noPowerOffOnBatteryCritical,
    @Default(false) bool noPowerOffOnBatteryFull,
    @Default(false) bool noPowerOffOnBatteryCharging,
    @Default(false) bool noPowerOffOnBatteryDischarging,
    @Default(false) bool noPowerOffOnBatteryNotCharging,
    @Default(false) bool noPowerOffOnBatteryUnknown,
    @Default(false) bool noPowerOffOnBatteryNotPresent,
    @Default(false) bool noPowerOffOnBatteryPresent,
    @Default(false) bool noPowerOffOnBatteryChargingAC,
    @Default(false) bool noPowerOffOnBatteryChargingUSB,
    @Default(false) bool noPowerOffOnBatteryChargingWireless,
    @Default(false) bool noPowerOffOnBatteryChargingUnknown,
    @Default(false) bool noPowerOffOnBatteryChargingNotCharging,
    @Default(false) bool noPowerOffOnBatteryChargingDischarging,
    @Default(false) bool noPowerOffOnBatteryChargingFull,
    @Default(false) bool noPowerOffOnBatteryChargingLow,
    @Default(false) bool noPowerOffOnBatteryChargingCritical,
    @Default(false) bool noPowerOffOnBatteryChargingNotPresent,
    @Default(false) bool noPowerOffOnBatteryChargingPresent,
  }) = _DeviceConfig;

  factory DeviceConfig.fromJson(Map<String, dynamic> json) => _$DeviceConfigFromJson(json);
}
